language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  # command to install dependencies
  - pip install . -r requirements.txt
script:
  # command to run tests
  - py.test --cov --doctest-modules
notifications:
  email:
    on_success: change
    on_failure: change
